// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asykivkirsjhpofndjbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzeWtpdmtpcnNqaHBvZm5kamJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjcxNzksImV4cCI6MjA3MDA0MzE3OX0.Vn_JYZB8sThwAuib2mcsbR9w-KEYoJuAcuXULIwLHpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});